### ISSUE TITLE
"'Box' object has no attribute 'Curfew_Enabled'"

### ISSUE THREAD

**Issue by peedub** [PetHubLocal/pethublocal#1]
Have got this up and running and appears to be mostly working, but in the logs I get the following error:
```
2022-06-23 00:35:09,520 : [ERROR] : Task exception was never retrieved
future: <Task finished name='Task-2' coro=<mqtt_start() done, defined at /usr/local/lib/python3.9/site-packages/pethublocal/frontend.py:198> exception=BoxKeyError("'Box' object has no attribute 'Curfew_Enabled'")>
Traceback (most recent call last):
  File "/usr/local/lib/py
```
Any idea what that might be related to?
I'm running it via docker in a separate VM. I can see the devices in Home Assistant but their states are unknown. Let me know if you need further info.

**Comment by plambrechtsen** [comment]
Ahhh yes.. I have seen it before and thought I had fixed it. Quick fix for that is adding into the config under the door the element
```
   "Curfew_Enabled": "",
```

It's because you have never set a curfew on the cloud, so the `start` response doesn't return anything. If you email me offline your `start.json` I can check what else I have missed, but that will be the problem.

**Comment by peedub** [comment]
Easy fix! Yes, this is a cat door if had issues with so removed it and reassess it but hadn't set up curfews again. I'll add this and let you know how I get on.

**Comment by plambrechtsen** [comment]
I need to fix the assumptions I make that elements in the `pethubconfig.json` will always exist and I need to add a wrapper to just add an empty element if it doesn't. Also working on curfew management as it's not part of the code at all but you can add it into the config as `HH:MM`. But will go into the browser interface as the date time picker in Home Assistant just didn't work as nicely as I wanted.
But glad to hear you're sorted.

**Comment by peedub** [comment]
Your tip fixed the cat door issue but now I have an error about the feeder:

future: <Task finished name='Task-2' coro=<mqtt_start() done, defined at /usr/local/lib/python3.9/site-packages/pethublocal/frontend.py:198> exception=AttributeError("'str' object has no attribute 'Bowl_Target'")>

That item is in the config file but has a value of [] or [10] if I set portioning to 10. Is it meant to be a list (assuming that's what the square brackets are for)?
