### ISSUE TITLE
Watchdog function for hub communication (call script at failure)

### ISSUE THREAD

**Issue by jacotec** [PetHubLocal/pethublocal#17]
As the issue #11 periodically occurs every few weeks, putting the hub to "red" and stop any functionality, I was thinking about a concept to automatically solve this issue.

In case of the "red" condition, you need to stop the local Mosquitto, delete /var/lib/mosquitto/mosquitto.db to remove the stuck echo MQTT message which kills the hub and then restart Mosquitto.

Can we implement a watchdog funcionality which calls a shell script to automatically solve the situation?

PHL should periodically get update messages from the hub and the connected devices even if no pet action is happening (status telegrams). Will it be possible to implement a kind of timer (maybe twice the time of the maximum interval between these status telegrams) which runs down and which is reloaded by any incoming telegram from the hub to PHL.

In case the timer runs down to 0 (which happens if the hub got stuck), it should call a shell script (i.e. watchdog.sh) in which the commands for this case can be executed (stop mosquitto, remove the database, restart mosquitto), then it reloads the timer again and so on.

I have no clue how to implement this in Python, maybe @plambrechtsen or someone else can help?

**Comment by flyize** [comment]
As a really ugly workaround, I think I'm going to turn persistence off and restart the mosquitto service nightly.

**Comment by jacotec** [comment]
Implemented with PR #22
